export const definitions = {
    types: {
        Providers: 'Map<AccountId,Provider>',
        ProviderAccounts: 'Map<GovernanceStatus<BTreeSet,AccountId>>',
        ServiceOrigins: 'Map<Hash,()>',
        CaptchaData: {
            provider: 'AccountId',
            dataset_id: 'Hash',
            captcha_type: 'u16',
        },
        CaptchaSolutionCommitments: 'Map<Hash,CaptchaSolutionCommitment>',
        ProviderStakeDefault: 'u128',
        Dapps: 'Map<AccountId,Dapp>',
        DappAccounts: 'Vec<AccountId>',
        Operators: 'Map<AccountId,Operator>',
        OperatorAccounts: 'Vec<AccountId>',
        OperatorStakeDefault: 'u64',
        OperatorFeeCurrency: 'Hash',
        DappUsers: 'Map<AccountId,User>',
        DappUserAccounts: 'Vec<AccountId>',
        Provider: {
            status: 'GovernanceStatus',
            balance: 'u128',
            fee: 'u32',
            payee: 'Payee',
            service_origin: 'Hash',
            dataset_id: 'Hash',
            dataset_id_content: 'Hash',
        },
        GovernanceStatus: {
            _enum: ['Active', 'Suspended', 'Deactivated'],
        },
        Payee: {
            _enum: ['Provider', 'Dapp', 'None'],
        },
        CaptchaSolutionCommitment: {
            account: 'AccountId',
            dataset_id: 'Hash',
            status: 'CaptchaStatus',
            contract: 'AccountId',
            provider: 'AccountId',
            completed_at: 'u64',
        },
        CaptchaStatus: {
            _enum: ['Pending', 'Approved', 'Disapproved'],
        },
        Dapp: {
            status: 'GovernanceStatus',
            balance: 'u128',
            owner: 'AccountId',
            min_difficulty: 'u16',
            client_origin: 'Hash',
        },
        Operator: {
            status: 'GovernanceStatus',
        },
        User: {
            correct_captchas: 'u64',
            incorrect_captchas: 'u64',
            last_correct_captcha: 'u64',
            last_correct_captcha_dapp_id: 'AccountId',
        },
        ProsopoError: {
            _enum: [
                'NotAuthorised',
                'ContractInsufficientFunds',
                'ContractTransferFailed',
                'ProviderExists',
                'ProviderDoesNotExist',
                'ProviderInsufficientFunds',
                'ProviderInactive',
                'ProviderServiceOriginUsed',
                'DuplicateCaptchaDataId',
                'DappExists',
                'DappDoesNotExist',
                'DappInactive',
                'DappInsufficientFunds',
                'CaptchaDataDoesNotExist',
                'CaptchaSolutionCommitmentDoesNotExist',
                'CaptchaSolutionCommitmentExists',
                'DappUserDoesNotExist',
                'NoActiveProviders',
                'DatasetIdSolutionsSame',
            ],
        },
        LastCorrectCaptcha: {
            before_ms: 'u32',
            dapp_id: 'AccountId',
        },
        RandomProvider: {
            provider_id: 'AccountId',
            provider: 'Provider',
            block_number: 'u32',
        },
    },
}
