export const definitions = {
    types: {
        Providers: 'Map<AccountId,ProsopoProvider>',
        ProviderAccounts: 'Map<ProsopoGovernanceStatus<BTreeSet,AccountId>>',
        ServiceOrigins: 'Map<Hash,()>',
        CaptchaData: 'Map<Hash,ProsopoCaptchaData>',
        CaptchaSolutionCommitments: 'Map<Hash,ProsopoCaptchaSolutionCommitment>',
        ProviderStakeDefault: 'u128',
        Dapps: 'Map<AccountId,ProsopoDapp>',
        DappAccounts: 'Vec<AccountId>',
        Operators: 'Map<AccountId,ProsopoOperator>',
        OperatorAccounts: 'Vec<AccountId>',
        OperatorStakeDefault: 'u64',
        OperatorFeeCurrency: 'Hash',
        DappUsers: 'Map<AccountId,ProsopoUser>',
        DappUserAccounts: 'Vec<AccountId>',
        ProsopoProvider: {
            status: 'ProsopoGovernanceStatus',
            balance: 'u128',
            fee: 'u32',
            payee: 'ProsopoPayee',
            service_origin: 'Hash',
            dataset_id: 'Hash',
            dataset_id_content: 'Hash',
        },
        ProsopoGovernanceStatus: {
            _enum: ['Active', 'Suspended', 'Deactivated'],
        },
        ProsopoPayee: {
            _enum: ['Provider', 'Dapp', 'None'],
        },
        ProsopoCaptchaData: {
            provider: 'AccountId',
            dataset_id: 'Hash',
            captcha_type: 'u16',
        },
        ProsopoCaptchaSolutionCommitment: {
            account: 'AccountId',
            dataset_id: 'Hash',
            status: 'ProsopoCaptchaStatus',
            contract: 'AccountId',
            provider: 'AccountId',
            completed_at: 'u64',
        },
        ProsopoCaptchaStatus: {
            _enum: ['Pending', 'Approved', 'Disapproved'],
        },
        ProsopoDapp: {
            status: 'ProsopoGovernanceStatus',
            balance: 'u128',
            owner: 'AccountId',
            min_difficulty: 'u16',
            client_origin: 'Hash',
        },
        ProsopoOperator: {
            status: 'ProsopoGovernanceStatus',
        },
        ProsopoUser: {
            correct_captchas: 'u64',
            incorrect_captchas: 'u64',
            last_correct_captcha: 'u64',
            last_correct_captcha_dapp_id: 'AccountId',
        },
        ProsopoError: {
            _enum: [
                'NotAuthorised',
                'ContractInsufficientFunds',
                'ContractTransferFailed',
                'ProviderExists',
                'ProviderDoesNotExist',
                'ProviderInsufficientFunds',
                'ProviderInactive',
                'ProviderServiceOriginUsed',
                'DuplicateCaptchaDataId',
                'DappExists',
                'DappDoesNotExist',
                'DappInactive',
                'DappInsufficientFunds',
                'CaptchaDataDoesNotExist',
                'CaptchaSolutionCommitmentDoesNotExist',
                'CaptchaSolutionCommitmentExists',
                'DappUserDoesNotExist',
                'NoActiveProviders',
                'DatasetIdSolutionsSame',
            ],
        },
        ProsopoLastCorrectCaptcha: {
            before_ms: 'u32',
            dapp_id: 'AccountId',
        },
        ProsopoRandomProvider: {
            provider_id: 'AccountId',
            provider: 'ProsopoProvider',
            block_number: 'u32',
        },
    },
}

export type definitionKeys = keyof typeof definitions.types
