name: "print_contexts"

inputs:
    INPUTS_CONTEXT:
        description: "The inputs context as json"
        required: false
    NEEDS_CONTEXT:
        description: "The needs context as json"
        required: false
    VARS_CONTEXT:
        description: "The vars context as json"
        required: false
    SECRETS_CONTEXT:
        description: "The secrets context as json"
        required: false
    STEPS_CONTEXT:
        description: "The steps context as json"
        required: false

runs:
    using: "composite"
    steps:

      - name: Print contexts
        shell: bash
        run: |
          echo "******************************"
          echo "github:" "${{ toJson(github) }}"
          echo "******************************"
          echo "env:" "${{ toJson(env) }}"
          echo "******************************"
          echo "vars:" "${{ inputs.VARS_CONTEXT }}"
          echo "******************************"
          echo "job:" "${{ toJson(job) }}"
          echo "******************************"
          echo "runner:" "${{ toJson(runner) }}"
          echo "******************************"
          echo "secrets:" "${{ inputs.SECRETS_CONTEXT }}"
          echo "******************************"
          echo "strategy:" "${{ toJson(strategy) }}"
          echo "******************************"
          echo "matrix:" "${{ toJson(matrix)}}"
          echo "******************************"
          echo "needs:" "${{ inputs.NEEDS_CONTEXT }}"
          echo "******************************"
          echo "inputs:" "${{ inputs.INPUTS_CONTEXT }}"
          echo "******************************"
          echo "steps:" "${{ inputs.STEPS_CONTEXT }}"
          echo "******************************"
