name: "print_contexts"

inputs:
    INPUTS_CONTEXT:
        description: "The inputs context as json"
        required: false
    NEEDS_CONTEXT:
        description: "The needs context as json"
        required: false
    VARS_CONTEXT:
        description: "The vars context as json"
        required: false
    SECRETS_CONTEXT:
        description: "The secrets context as json"
        required: false
    STEPS_CONTEXT:
        description: "The steps context as json"
        required: false

runs:
    using: "composite"
    steps:

      - name: Print contexts
        shell: bash
        run: |
            echo "**** github ****"
            cat <<'EOF'
            ${{ toJson(github) }}
            EOF
            
            echo "**** env ****"
            cat <<'EOF'
            ${{ toJson(env) }}
            EOF
            
            echo "**** vars ****"
            cat <<'EOF'
            ${{ inputs.VARS_CONTEXT }}
            EOF

            echo "**** job ****"
            cat <<'EOF'
            ${{ toJson(job) }}
            EOF

            echo "**** runner ****"
            cat <<'EOF'
            ${{ toJson(runner) }}
            EOF

            echo "**** secrets ****"
            cat <<'EOF'
            ${{ inputs.SECRETS_CONTEXT }}
            EOF

            echo "**** strategy ****"
            cat <<'EOF'
            ${{ toJson(strategy) }}
            EOF

            echo "**** matrix ****"
            cat <<'EOF'
            ${{ toJson(matrix)}}
            EOF

            echo "**** needs ****"
            cat <<'EOF'
            ${{ inputs.NEEDS_CONTEXT }}
            EOF

            echo "**** inputs ****"
            cat <<'EOF'
            ${{ inputs.INPUTS_CONTEXT }}
            EOF

            echo "**** steps ****"
            cat <<'EOF'
            ${{ inputs.STEPS_CONTEXT }}
            EOF
