name: Prosopo Website Tests

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ENVIRONMENT: development
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone prosopo-website
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          repository: prosopo/prosopo-website
          path: prosopo-website

      - name: Install dependencies
        run: |
          cd prosopo-website
          ls
          pwd
          npm install

      - name: Build Static Website
        run: |
          cd prosopo-website
          npm run build
          # Make sure all referenced scripts are present
          grep -Poir '<script src=\"(\/[^>]+>)' dist | grep -oh '".*"' | sort | uniq | xargs printf -- 'dist%s\n' | xargs stat

      - name: Build TypeScript Functions
        run: |
          cd prosopo-website/netlify
          npm i
          npm run build
