/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute a JA4 TLS fingerprint from raw ClientHello bytes.
 *
 * Uses the vendored JA4 parser in `src/ja4.rs`. Parity with any external
 * reference implementation is checked by the vitest suite in
 * packages/provider/src/tests/unit/api/ja4.unit.test.ts.
 */
export declare function calculateJa4(data: Buffer): string
