// Copyright 2021-2026 Prosopo (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute a JA4 TLS fingerprint from raw ClientHello bytes.
 *
 * Delegates to the `prosopo-ja4` crate on crates.io — the same
 * implementation the protect edge stack (bumblebee) uses, so both produce
 * byte-identical fingerprints for the same input.
 */
export declare function calculateJa4(data: Buffer): string
