/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute a JA4 TLS fingerprint from raw ClientHello bytes.
 *
 * Delegates to the `prosopo-ja4` crate on crates.io — the same
 * implementation the protect edge stack (bumblebee) uses, so both produce
 * byte-identical fingerprints for the same input.
 */
export declare function calculateJa4(data: Buffer): string
