[sources.stdin]
type = "stdin"
decoding.codec = "json"

[transforms.add_env_var]
type = "remap"
inputs = ["stdin"]
source = '''
del(.id)
del(.from)
.name=.Actor.Attributes.name
.image=.Actor.Attributes.image
del(.Actor)
del(.scope)
del(.time)
del(.timeNano)
.action=del(.Action)
.type=del(.Type)
del(.host)
del(.source_type)
del(.timestamp)
'''

[sinks.console]
type = "console"
inputs = ["add_env_var"]
encoding.codec = "json"
