export { default as commandDeploy } from './deploy.js'
export { default as commandAuth } from './auth.js'
export { default as commandGetDapps } from './getDapps.js'
export { default as commandGetDapp } from './getDapp.js'
export { default as commandTerminal } from './terminal.js'
