export { default as ReloadIcon } from './icons/reload.svg'
export { default as CoverPhoto } from './images/cover.png'
export { default as LoadingIcon } from './icons/loading.svg'
export { default as Logo } from './logo.svg'
export { default as PolkadotJsIcon } from './images/polkadotjs.png'
export { default as TalismanIcon } from './images/talisman.png'
export { default as SubwalletIcon } from './icons/subwallet.svg'
