import { CheckIcon, ChevronDownIcon, ExclamationCircleIcon } from '@heroicons/react/solid';

export { default as BidsIcon } from './icons/bids.svg';
export { default as CheckCircle } from './icons/CheckCircle.svg';
export { default as CopyIcon } from './icons/copy.svg';
export { default as DiscordIcon } from './icons/discord.svg';
export { default as DotsIcon } from './icons/dots.svg';
export { default as FavouriteIcon } from './icons/favourite.svg';
export { default as InstagramIcon } from './icons/instagram.svg';
export { default as PriceIcon } from './icons/price.svg';
export { default as ReloadIcon } from './icons/reload.svg';
export { default as SearchIcon } from './icons/search.svg';
export { default as SpinnerIcon } from './icons/spinner.png';
export { default as SunIcon } from './icons/sun.svg';
export { default as TelegramIcon } from './icons/telegram.svg';
export { default as TwitterIcon } from './icons/twitter.svg';
export { default as VerifiedIcon } from './icons/verified.svg';
export { default as CoverPhoto } from './images/cover.png';
export { default as UploadIcon } from './images/upload-icon.svg';
export { default as WalletImage } from './images/wallet-image.svg';
export { default as WalletPageCover } from './images/wallet-page-cover.svg';
export { default as Logo } from './logo.svg';
export { ChevronDownIcon, CheckIcon, ExclamationCircleIcon };
