# https://docs.docker.com/cloud/ecs-integration/
version: '3.8'
services:
  substrate:
    image: prosopo/substrate:demo-v1.0.4
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
  database:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=prosopo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
  provider:
    # TODO update provider image
    image: prosopo/provider:v1.0.5
    environment:
      - NODE_ENV=production
      - DAPP_CONTRACT_ADDRESS=5GoHpdidCX62uE3wuQagVWhf4Un1gVten4NZ6k72Hd74WYYr
      - DATABASE_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "3000:3000"
    depends_on:
      - substrate
      - database
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html
# secrets:
#   env_demo:
#     name: "arn:aws:secretsmanager:eu-west-1:333775583992:secret:env.demo-xS1Weo"
#     external: true

x-aws-vpc: vpc-0d475f14c1385d682
x-aws-loadbalancer: arn:aws:elasticloadbalancing:eu-west-1:333775583992:loadbalancer/net/demo-net/c964b999910c2e7d
x-aws-cloudformation:
  Resources:
    SubstrateTCP9944Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191"
        Protocol: TLS
        Port: 9944
    SubstrateTCP9933Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191"
        Protocol: TLS
        Port: 9933
    ProviderTCP3000Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191"
        Protocol: TLS
        Port: 3000
