version: '3.4'
services:
  substrate-node:
    image: prosopo/substrate-node:dev
    build:
      context: .
      dockerfile: ./images/substrate-node.build.dockerfile
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
#    volumes:
#      - ./chain-data:/chain-data
