# https://docs.docker.com/cloud/ecs-integration/
services:
    database:
        image: mongo:7.0.14
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE=prosopo
    provider:
        # TODO update provider image
        image: prosopo/provider:v1.0.5
        environment:
            - NODE_ENV=production
            - PROSOPO_SITE_KEY=5GoHpdidCX62uE3wuQagVWhf4Un1gVten4NZ6k72Hd74WYYr
            - PROSOPO_DATABASE_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        ports:
            - '3000:3000'
        depends_on:
            - database

# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html
# secrets:
#   env_demo:
#     name: "arn:aws:secretsmanager:eu-west-1:333775583992:secret:env.demo-xS1Weo"
#     external: true

x-aws-vpc: vpc-0d475f14c1385d682
x-aws-loadbalancer: arn:aws:elasticloadbalancing:eu-west-1:333775583992:loadbalancer/net/demo-net/c964b999910c2e7d
x-aws-cloudformation:
    Resources:
        ProviderTCP3000Listener:
            Properties:
                Certificates:
                    - CertificateArn: 'arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191'
                Protocol: TLS
                Port: 3000
