# usage:
# docker-compose -f docker-compose.provider.yml -f docker-compose.provider.dev.yml up
# this overrides the docker-compose.provider.yml file with the definitions below

services:
    provider1:
        profiles: null
        ports: '9229:9229'
        depends_on: 
            database:
                condition: service_healthy
            # no caddy
            # no vector
    provider2:
        profiles: null
        ports: '9339:9339'
        depends_on:
            database:
                condition: service_healthy
            # no caddy
            # no vector
    database:
        container_name: database
        ports: '21017:21017'
        profiles: null
        depends_on: []
            # no caddy
            # no vector
    caddy:
        container_name: caddy
        profiles:
            - disabled # disable caddy
    vector:
        container_name: vector
        profiles:
            - disabled # disable vector
