name: "npm"

runs:
    using: "composite"
    steps:

      - uses: ./../restore_npm_cache

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          
      - name: install npm
        shell: bash
        run: |
          npm i -g "npm@$(jq -r .engines.npm < package.json)"

      - name: install project
        shell: bash
        run: |
          npm ci
