version: '3.4'
services:
  dapp-build:
    image: prosopo/dapp-build:latest
    volumes:
      - type: bind
        source: .
        target: /usr/src/dapp-example
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    build:
      context: .
      dockerfile: ./dapp-example/docker/contracts.dapp.dockerfile
      args:
        # amd64
        BASE: paritytech
        TAG: latest
        ARCHITECTURE: x86_64

        # arm64
        # BASE: prosopo
        # TAG: m1-latest
        # ARCHITECTURE: aarch64
    links:
      - substrate-node
    #command: "tail -f /dev/null"
  substrate-node:
    image: prosopo/substrate:v1.0.0
    build:
      context: ./docker/
      dockerfile: Substrate.dockerfile
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
