// Copyright 2021-2026 Prosopo (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { generateMnemonic } from "@prosopo/keyring";
import { LogLevel, getLogger, parseLogLevel } from "@prosopo/logger";

const logger = getLogger(
	parseLogLevel(process.env.PROSOPO_LOG_LEVEL || LogLevel.enum.info),
	"generateSelfHostedEnv",
);

interface Args {
	host: string;
	output: string;
	force: boolean;
}

const usage = `
Generate a complete .env file for a self-hosted Procaptcha provider.

  npx tsx ./dev/scripts/src/scripts/generateSelfHostedEnv.ts --host captcha.example.com

Options:
  --host <domain>   Hostname clients will reach this provider on (required)
  --output <path>   Where to write (default: .env)
  --force           Overwrite the output file if it already exists
`;

const parseArgs = (argv: string[]): Args => {
	const flagValue = (flag: string): string | undefined => {
		const index = argv.indexOf(flag);
		if (index === -1) return undefined;
		const value = argv[index + 1];
		return value && !value.startsWith("--") ? value : undefined;
	};

	const host = flagValue("--host");
	if (!host) {
		throw new Error(`--host is required.\n${usage}`);
	}
	// A bare hostname keeps the generated CADDY_DOMAIN and PROSOPO_PROVIDER_LIST
	// consistent: Caddy wants the name alone as its certificate subject, while
	// the provider list wants it as an https:// origin.
	if (host.includes("://") || host.includes("/")) {
		throw new Error(
			`--host must be a bare hostname such as captcha.example.com, not a URL. Got: ${host}`,
		);
	}

	return {
		host,
		output: flagValue("--output") ?? ".env",
		force: argv.includes("--force"),
	};
};

/**
 * base64url rather than base64: the password is interpolated into a MongoDB
 * connection string unescaped (see `getMongoURI`), so it must not contain
 * `@`, `:`, `/` or `+`. base64url emits only `[A-Za-z0-9_-]`, which is also
 * safe to leave unquoted in a .env file.
 */
const generatePassword = (): string => randomBytes(24).toString("base64url");

const buildEnvFile = async (host: string): Promise<string> => {
	const [providerMnemonic, providerAddress] = await generateMnemonic();
	const [siteKeyMnemonic, siteKeyAddress] = await generateMnemonic();
	const databasePassword = generatePassword();
	const redisPassword = generatePassword();

	logger.info(() => ({
		data: { siteKeyAddress, providerAddress },
		msg: "Accounts generated",
	}));

	return `# Generated by generateSelfHostedEnv.ts for ${host}.
# Contains private keys and passwords — keep it out of version control.

NODE_ENV=production
PROSOPO_DEFAULT_ENVIRONMENT=production
PROSOPO_LOG_LEVEL=info

# Read by the provider as its own host identity, and by Caddy as the
# certificate subject.
CADDY_DOMAIN=${host}

# Points the widget and your server-side verifier at this provider instead of
# Prosopo's fleet. Accepts several comma-separated URLs, or the provider-list
# JSON, if you run more than one node.
PROSOPO_PROVIDER_LIST=https://${host}

# The shipped Caddyfile lists two upstreams so Prosopo can run two provider
# versions side by side. A self-hosted node points both at its one provider.
CADDY_PROVIDER_CONTAINER_NAME=provider
CADDY_PROVIDER_PORT=9229
CADDY_PROVIDER_PORT2=9229
CADDY_CLIENT_RATE_LIMIT_EVENTS=200
CADDY_CLIENT_RATE_LIMIT_WINDOW=1m
CADDY_RATE_LIMIT_EVENTS=100
CADDY_RATE_LIMIT_WINDOW=1m

PROSOPO_DATABASE_HOST=mongo
PROSOPO_DATABASE_PORT=27017
PROSOPO_DATABASE_NAME=prosopo
PROSOPO_DATABASE_USERNAME=root
PROSOPO_DATABASE_PASSWORD=${databasePassword}

REDIS_CONNECTION_URL=redis://redis:6379
REDIS_CONNECTION_PASSWORD=${redisPassword}

# Identifies this provider. Admin shares the account because it only gates the
# provider's own maintenance endpoints.
PROSOPO_PROVIDER_ADDRESS=${providerAddress}
PROSOPO_PROVIDER_MNEMONIC="${providerMnemonic}"
PROSOPO_ADMIN_ADDRESS=${providerAddress}
PROSOPO_ADMIN_MNEMONIC="${providerMnemonic}"

# The site key. The address is the public data-sitekey value for your pages;
# the mnemonic is used by @prosopo/server to verify tokens.
PROSOPO_SITE_KEY=${siteKeyAddress}
PROSOPO_SITE_PRIVATE_KEY="${siteKeyMnemonic}"

# IP reputation is optional, but both variables must be present or the provider
# exits on a config error. Left as placeholders, IP metadata comes from the
# MaxMind databases baked into the image instead.
PROSOPO_IPAPI_URL=https://ipapi.example.invalid
PROSOPO_IPAPI_KEY=unused

MAXMIND_DB_PATH=./GeoLite2-Country.mmdb
MAXMIND_CITY_DB_PATH=./GeoLite2-City.mmdb
MAXMIND_ASN_DB_PATH=./GeoLite2-ASN.mmdb
`;
};

const main = async (): Promise<void> => {
	const args = parseArgs(process.argv.slice(2));
	const outputPath = path.resolve(process.cwd(), args.output);

	if (fs.existsSync(outputPath) && !args.force) {
		throw new Error(
			`${outputPath} already exists. Pass --force to overwrite it, but note that this regenerates every key and password: an existing provider would lose its identity and its database credentials.`,
		);
	}

	const contents = await buildEnvFile(args.host);
	// 0o600 because this file holds two mnemonics and two passwords.
	fs.writeFileSync(outputPath, contents, { mode: 0o600 });

	logger.info(() => ({
		data: { outputPath },
		msg: "Environment file written",
	}));
};

main()
	.then(() => process.exit(0))
	.catch((err: unknown) => {
		logger.error(() => ({ err, msg: "Failed to generate environment file" }));
		process.exit(1);
	});
