module.exports = {
    entryPoints: [
        'app/**/*.ts',
        'app/**/*.tsx',
        'app/**/*.js',
        'app/**/*.jsx',
        'app/**/*.json',
        'components/**/*.ts',
        'components/**/*.tsx',
        'components/**/*.js',
        'components/**/*.jsx',
        'components/**/*.json',
        'contexts/**/*.ts',
        'contexts/**/*.tsx',
        'contexts/**/*.js',
        'contexts/**/*.jsx',
        'contexts/**/*.json',
        'mocks/**/*.ts',
        'mocks/**/*.tsx',
        'mocks/**/*.js',
        'mocks/**/*.jsx',
        'mocks/**/*.json',
        'services/**/*.ts',
        'services/**/*.tsx',
        'services/**/*.js',
        'services/**/*.jsx',
        'services/**/*.json',
        'types/**/*.ts',
        'types/**/*.tsx',
        'types/**/*.js',
        'types/**/*.jsx',
        'types/**/*.json',
    ],
    includes: ['app', 'components', 'contexts', 'mocks', 'services', 'types'],
    extends: '../typedoc.base.config.js',
}
