[sources.in]
type = "stdin"

[sources.cmd_in]
type = "exec"
command = ["docker", "events", "--format", "json"]
decoding.codec = "json"
mode = "streaming"

[sinks.out]
type = "console"
inputs = ["in"]
encoding.codec = "json"

[sinks.cmd_out]
type = "console"
inputs = ["cmd_in"]
encoding.codec = "json"
