/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * blake2b-256 hex of a single string. Equivalent to `blake2AsHex(input)`
 * from @prosopo/util-crypto (default 256-bit output, "0x" prefix).
 */
export declare function hexHash(input: string): string
/**
 * blake2b-256 hex of `parts.join("")`. Equivalent to
 * `hexHashArray(parts)` from @prosopo/util-crypto.
 */
export declare function hexHashArray(parts: Array<string>): string
/**
 * Leaf hash for a single captcha solution, byte-identical to
 * `computeCaptchaSolutionHash` in @prosopo/datasets. `solution` is sorted
 * lexicographically before hashing.
 */
export declare function computeCaptchaSolutionHash(captchaId: string, captchaContentId: string, solution: Array<string>, salt: string): string
/**
 * Compute every layer of the Merkle tree, from the leaves up to (and
 * including) the single-element root layer. Uses the JS tree layout in
 * @prosopo/datasets (blake2b-256 of joined-hex-strings, odd tail duplicated
 * per layer, single leaf yields a one-layer tree whose root == the leaf).
 *
 * Throws `InvalidArg` if `leaves` is empty — the JS caller
 * (buildTreeAndGetCommitmentId) always throws in that case, so this mirrors it.
 */
export declare function buildMerkleLayers(leaves: Array<string>): Array<Array<string>>
