# vector config which takes the logs from a docker container running `docker events`

# `docker events` should be piped to stdin
[sources.stdin]
type = "stdin"
decoding.codec = "json"

# delete useless info and add the host to identify what machine the logs are coming from
[transforms.trim]
type = "remap"
inputs = ["stdin"]
source = '''
.host="$HOST"
del(.id)
del(.from)
del(.host)
del(.Type)
.name=.Actor.Attributes.name
del(.Actor)
del(.scope)
del(.time)
del(.timeNano)
del(.source_type)
del(.timestamp)
'''

# print to console
[sinks.console]
type = "console"
inputs = ["trim"]
encoding.codec = "json"

# send to openobserve
[sinks.openobserve]
type = "http"
inputs = ["trim"]
uri = "$URL_EVENTS"
method = "post"
auth.strategy = "basic"
auth.user = "$USERNAME"
auth.password = "$PASSWORD"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
