[sources.in]
type = "docker_logs"
include_labels = ["vector.provider=true"]

[transforms.format]
type = "remap"
inputs = ["in"]
source = '''
.host="$HOST"
del(.container_created_at)
del(.container_id)
del(.host)
del(.image)
del(.label)
del(.source_type)
del(.stream)
del(.timestamp)
'''

# print to console
[sinks.console]
type = "console"
inputs = ["format"]
encoding.codec = "json"

# send to openobserve
[sinks.openobserve]
type = "http"
inputs = ["format"]
uri = "$URL_PROVIDER"
method = "post"
auth.strategy = "basic"
auth.user = "$USERNAME"
auth.password = "$PASSWORD"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
