name: contract_release_process

on:
    push:
        branches:
            - 'main'
        paths:
            - 'package.json'
            - '.github/workflows/contract_release_process.yml'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - uses: actions/checkout@v3

            - run: mkdir -p protocol/cargo-cache
            - run: mkdir -p protocol/target
            - run: mkdir -p node_modules
            - run: mkdir -p .cache/Cypress

            - name: Restore cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      protocol/cargo-cache
                      protocol/target
                      node_modules
                      .cache/Cypress
                  # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
                  # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
                  # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
                  key: some-unused-cache-key
                  restore-keys: |
                      project-cache-${{ runner.os }}-${{ runner.arch }}-

            # Get the provider image version from the root package.json and the latest package version from npm
            - name: Check provider version bump
              id: check_provider_image_version
              run: |
                  # get the next provider version number from the package.json
                  NEXT=$(cat package.json | jq -r '.version')
                  # get the current provider version number from npm
                  CURRENT=$(npm view @prosopo/provider version)
                  NEXT_MAJOR=$(echo $NEXT | cut -d '.' -f 1)
                  NEXT_MINOR=$(echo $NEXT | cut -d '.' -f 2)
                  NEXT_PATCH=$(echo $NEXT | cut -d '.' -f 3)
                  CURRENT_MAJOR=$(echo $CURRENT | cut -d '.' -f 1)
                  CURRENT_MINOR=$(echo $CURRENT | cut -d '.' -f 2)
                  CURRENT_PATCH=$(echo $CURRENT | cut -d '.' -f 3)
                  # compare major versions for bump
                  if [[ $NEXT_MAJOR -gt $CURRENT_MAJOR ]]; then
                    echo "major version bump detected"
                    echo "bump=true" >> $GITHUB_OUTPUT
                  elif [[ $NEXT_MINOR -gt $CURRENT_MINOR ]]; then
                    echo "minor version bump detected"
                    echo "bump=true" >> $GITHUB_OUTPUT
                  elif [[ $NEXT_PATCH -gt $CURRENT_PATCH ]]; then
                    echo "patch version bump detected"
                    echo "bump=true" >> $GITHUB_OUTPUT
                  else
                    echo "no version bump detected"
                    echo "bump=false" >> $GITHUB_OUTPUT
                  fi
                  echo "PROVIDER_IMAGE_VERSION=$NEXT" >> $GITHUB_ENV

            - name: Build the contract sources
              if: steps.check_provider_image_version.outputs.bump == 'true'
              run: |
                  set -e  # Exit immediately if a command exits with a non-zero status.

                  npm ci

                  cd protocol/dev
                  npm run build
                  npm run cli -- clean --docker
                  npm run cli -- build --docker --release

                  cd ../..

            - name: Create Release
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ env.PROVIDER_IMAGE_VERSION }}
                  release_name: Release ${{ env.PROVIDER_IMAGE_VERSION }}
                  body: Automated release of contract sources for npm version ${{ env.PROVIDER_IMAGE_VERSION }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Contract ABI
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-abi
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/captcha/captcha.json
                  asset_name: captcha.json
                  asset_content_type: application/json
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Contract WASM
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-wasm
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/captcha/captcha.wasm
                  asset_name: captcha.wasm
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Contract
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-contract
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/captcha/captcha.contract
                  asset_name: captcha.contract
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Proxy ABI
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-abi-proxy
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/proxy/proxy.json
                  asset_name: proxy.json
                  asset_content_type: application/json
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Proxy WASM
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-wasm-proxy
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/proxy/proxy.wasm
                  asset_name: proxy.wasm
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Proxy
              if: steps.check_provider_image_version.outputs.bump == 'true'
              id: upload-release-asset-contract-proxy
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./protocol/target/ink/proxy/proxy.contract
                  asset_name: proxy.contract
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
