name: create_diagram
on:
    workflow_dispatch: {}
    pull_request:
        branches:
            - main
jobs:
    get_data:
        runs-on: ubuntu-latest
        steps:
            - uses: prosopo/captcha/.github/actions/print_vars.yml@main

            - uses: actions/checkout@v3
            - uses: githubocto/repo-visualizer@main
              with:
                  branch: repo-diagram
