# Check for dependent issues and pull requests in GitHub repositories.

name: dependent_issues

on:
    pull_request:
        types:
            - opened
            - edited
            - closed
            - reopened
            # Makes sure we always add status check for PRs. Useful only if
            # this action is required to pass before merging. Otherwise, it
            # can be removed.
            - synchronize
    issue_comment:
        types: [created, deleted, edited]

    # Schedule a daily check. Useful if you reference cross-repository
    # issues or pull requests. Otherwise, it can be removed.
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request }}
        steps:
            - uses: z0al/dependent-issues@v1
              env:
                  # (Required) The token to use to make API calls to GitHub.
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # (Optional) The token to use to make API calls to GitHub for remote repos.
                  GITHUB_READ_TOKEN: ${{ secrets.DEPENDENT_ISSUES_PAT }}

              with:
                  # (Optional) The label to use to mark dependent issues
                  label: blocked

                  # (Optional) Enable checking for dependencies in issues.
                  # Enable by setting the value to "on". Default "off"
                  check_issues: on

                  # (Optional) Ignore dependabot PRs.
                  # Enable by setting the value to "on". Default "off"
                  ignore_dependabot: off

                  # (Optional) A comma-separated list of keywords. Default
                  # "depends on, blocked by"
                  keywords: depends on, blocked by, blocked

                  # (Optional) A custom comment body. It supports `{{ dependencies }}` token.
                  comment: >
                      :hourglass_flowing_sand: Blocked by: {{ dependencies }}.

                      :bell: I'll update this comment when the blocking issues/PRs are closed.

                      :thought_balloon: From [Dependent Issues (:robot:)](https://github.com/z0al/dependent-issues)
