# Lint the codebase

name: lint

on:
    pull_request:
        branches: [main, dev, staging, release/*]
        types: 
            - opened # when a PR is opened
            - synchronize # when a PR is pushed to
            - reopened # when a PR is reopened
            - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    CARGO_TERM_COLOR: always
    NODE_OPTIONS: "--max-old-space-size=4096"

defaults:
    run:
        shell: bash

jobs:
    check:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - name: Setup
              uses: ./.github/setup@${{ github.ref_name }}
              with:
                cache: true
                install: true

            - run: npm run -w @prosopo/lint build

            - run: npm run lint

