name: migrate_new_contract
on:
    pull_request:
        branches:
            - 'main'
    workflow_dispatch:

jobs:
    get-latest-release:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch the latest release and list assets
              uses: actions/github-script@v6
              with:
                  script: |
                      const { data } = await github.rest.releases.getLatest({
                        owner: context.repo.owner,
                        repo: context.repo.repo
                      });
                      console.log("Assets in the latest release:");
                      data.assets.forEach(asset => {
                        console.log(`- ${asset.name}`);
                      });
