name: print_vars

on:
    workflow_call:
    workflow_dispatch:

jobs:
    print_vars:
        runs-on: ubuntu-latest
        steps:
          - name: github context
            run: echo "${{ toJson(github) }}"
          - name: env context
            run: echo "${{ toJson(env) }}"
          - name: vars context
            run: echo "${{ toJson(vars) }}"
          - name: job context
            run: echo "${{ toJson(job) }}"
          - name: steps context
            run: echo "${{ toJson(steps) }}"
          - name: runner context
            run: echo "${{ toJson(runner) }}"
          - name: secrets context
            run: echo "${{ toJson(secrets) }}"
          - name: strategy context
            run: echo "${{ toJson(strategy) }}"
          - name: matrix context
            run: echo "${{ toJson(matrix) }}"
          - name: needs context
            run: echo "${{ toJson(needs) }}"
          - name: inputs context
            run: echo "${{ toJson(inputs) }}"
