name: tmp2

on:
    pull_request:
        branches:
            - 'develop'
            - 'main'
        paths:
            - 'protocol/**'
            - '.github/workflows/**'

env:
    CARGO_TERM_COLOR: always
    GH_TOKEN: ${{ github.token }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - run: mkdir -p protocol/cargo-cache
            - run: mkdir -p protocol/target
            - run: mkdir -p node_modules

            - name: Restore protocol cache
              uses: actions/cache/restore@v3
              id: cache
              with:
                  path: |
                      protocol/cargo-cache
                      protocol/target
                      node_modules
                  # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
                  # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
                  # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
                  key: some-unused-cache-key
                  restore-keys: |
                      protocol-${{ runner.os }}-${{ runner.arch }}-

            - name: ls
              run: |
                  set -x
                  ls -la
                  ls -la protocol/cargo-cache
                  ls -la protocol/target/* || true

            - name: Build contracts
              id: build
              run: |
                  cd protocol/dev
                  npm run cli -- build --docker "prosopo/contracts-ci-linux:3.0.1"
            
            - name: ls
              run: |
                  set -x
                  ls -la
                  ls -la protocol/cargo-cache
                  ls -la protocol/target/* || true